### PR TITLE
Move to 24 hour (UTC Date) key retrieval windows

### PR DESCRIPTION
**Pull request by burke**
Based on guidance in https://developers.google.com/android/exposure-notifications/exposure-key-file-format

### CODE REVIEW

**Comment by henrytao-me** [comment]
Cam we ship this PR asap? Other team is waiting for this end to end test, I think.

**Comment by burke** [comment]
Yup I'll try to get it done today.

**Comment by burke** [comment]
Ok I think this is good now; tests are passing again. I'm happy to either merge or wait for mobile to get the integration updates done, let me know what you'd prefer.

**Comment by henrytao-me** [comment]
Let's merge it. We can fix forward if necessary. I will test mobile tonight. 👍 🙇

**Pull request merged**
